### PR TITLE
fix to work with recent Async library updates

### PR DESCRIPTION
**Pull request by drewsdunne**
Nothing was working due to the pipe not being written to without the if_closed argument. Also Std stub no longer necessary.

### CODE REVIEW

**Comment by lpw25** [comment]
Sorry for the extremely slow response. I think the opam file you've added isn't quite right. The change to the `write` function seems to have happened in version [113.00.00](https://github.com/janestreet/async_unix/commit/133dce5bd77777913db90d75692535d31625dcac) so that should probably be the new lower bound. I also would prefer not to have an upper bound. The main async pacakges have them because they do synchronized releases, but this library should not need to be updated for each async release.

**Comment by drewsdunne** [comment]
Ah yes I didn't personally add the opam file, I should have checked it more carefully before I merged the PR. I agree no upper bound is needed.

**Comment by drewsdunne** [comment]
Alright, it's been updated and hopefully that should work.

**Comment by lpw25** [comment]
Thanks. I've merged it now and I'll make a new release on opam by the end of the week.

**Pull request merged**
